version: "3.3"
services:
  smoke_test_catalogue_api_stage:
    image: smoke_test_catalogue_api_stage
    build:
      context: ./smoke_tests
  diff_tool:
    image: diff_tool
    build:
      context: ./diff_tool
  internal_model_tool:
    image: internal_model_tool
    build:
      context: ./
      dockerfile: ./internal_model_tool/Dockerfile
