version: "3.3"

services:
  smoke_test_catalogue_api_stage:
    image: smoke_test_catalogue_api_stage
    build:
      context: ./smoke_tests
  diff_tool:
    image: diff_tool
    build:
      context: ./diff_tool
  concepts_api:
    image: uk.ac.wellcome/concepts_api:${CONTAINER_TAG:-test}
    build:
      context: .
      dockerfile: ./concepts/Dockerfile
