steps:
  - command: .buildkite/scripts/run_autoformat.py
    label: "autoformat"
    agents:
      queue: "scala"

    # We increase the priority of this task because it may push a commit
    # and trigger a new build; if so, we want that to happen ASAP.
    priority: 1

  - label: "{{ matrix }}"
    command: ".buildkite/scripts/run_scala_task.sh {{ matrix }} --is-library"
    matrix:
      - "display"
      - "search_common"
      - "stacks"

    agents:
      queue: "scala"

  - label: "{{ matrix }}"
    command: ".buildkite/scripts/run_scala_task.sh {{ matrix }}"

    matrix:
      setup:
        - "search"
        - "items"
        - "requests"

    agents:
      queue: "scala"

  - label: "snapshot generator"
    command: ".buildkite/scripts/run_scala_task.sh snapshot_generator snapshots/snapshot_generator"

    agents:
      queue: "scala"

  - label: "Concepts API (run tests)"
    key: "concepts-test"
    plugins:
      - docker-compose#v3.9.0:
          run: "concepts"
          command: ["yarn", "test"]

  - label: "Concepts API (publish image)"
    depends_on:
      - "concepts-test"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.9.0:
          push:
            - concepts:756629837203.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/concepts:ref.${BUILDKITE_COMMIT}
            - concepts:756629837203.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/concepts:latest

  - command: .buildkite/scripts/test_rank.sh
    label: "rank"
    env:
      QUERY_ENV: "candidate"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"

  - wait

  - label: trigger stage deploy
    branches: "main"
    trigger: "catalogue-api-deploy-stage"
    async: true
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
