steps:
  - command: .buildkite/scripts/run_autoformat.py
    label: "autoformat"
  - wait
  - command: .buildkite/scripts/run_job.py display
    label: "display"
  - command: .buildkite/scripts/run_job.py search_common
    label: "search_common"
  - command: .buildkite/scripts/run_job.py stacks
    label: "stacks_common"
  - wait
  - command: .buildkite/scripts/run_job.pyrun_)jo search
    label: "Search API (Works & Images)"
  - command: .buildkite/scripts/run_job.py items
    label: "Stacks: Items API"
  - command: .buildkite/scripts/run_job.py requests
    label: "Stacks: Requests API"
  - command: .buildkite/scripts/run_job.py snapshot_generator
    label: "snapshot generator"
  - wait
  - command: .buildkite/scripts/tag_commit_as_latest.py
    label: "tag commit as latest"

  - wait

  - label: trigger stage deploy
    branches: "main"
    trigger: "catalogue-api-deploy-stage"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
