steps:
  - label: "Deploy (catalogue stage)"
    branches: "main"
    command: |
      ENV_TAG="env.staging" ./builds/update_ecr_image_tag.sh \
        uk.ac.wellcome/concepts \
        uk.ac.wellcome/items \
        uk.ac.wellcome/search

      CLUSTER="catalogue-api-2021-04-26" ./builds/deploy_ecs_services.sh \
        stage-concepts-api \
        stage-items-api \
        stage-search-api

    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"

    agents:
      queue: nano

  - label: "Deploy (requests stage)"
    branches: "main"
    command: |
      ENV_TAG="env.staging" ./builds/update_ecr_image_tag.sh \
        uk.ac.wellcome/requests
      CLUSTER="identity-stage" ./builds/deploy_ecs_services.sh \
        requests-stage

    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::770700576653:role/identity-ci"

    agents:
      queue: nano

  - wait

  - label: "Smoke Tests: Catalogue API (stage)"
    branches: "main"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::130871440101:role/experience-ci"
      - docker-compose#v3.5.0:
          run: smoke_test_catalogue_api_stage
          command: ["yarn", "run", "smokeTestCatalogueApiStage"]
          env:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
            - AWS_REGION=eu-west-1

  - label: "E2E Tests: PROD Front-end / STAGE Catalogue API"
    branches: "main"
    trigger: "experience-e2e"
    build:
      env:
        PLAYWRIGHT_BASE_URL: https://wellcomecollection.org
        USE_STAGE_APIS: true

  - label: "Rank tests: Catalogue API (stage)"
    command: ./.buildkite/scripts/test_rank.sh
    env:
      QUERY_ENV: "staging"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"

  - wait

  - label: trigger prod deploy
    branches: "main"
    trigger: "catalogue-api-deploy-prod"
    async: true
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
