steps:
  - command: |
      ./builds/run_formatting.sh
      .buildkite/scripts/push_autoformatting_changes.sh
      ./builds/run_linting.sh
    label: "autoformat"
    agents:
      queue: "scala"

    # We increase the priority of this task because it may push a commit
    # and trigger a new build; if so, we want that to happen ASAP.
    priority: 1

    # It's only here so that I can see it running on normal builds
    # instead of just prod deployments.
  - label: "Diff tool: Compare stage & prod - DELETEME"
    artifact_paths: "reports/*"
    plugins:
      - docker-compose#v3.5.0:
          run: diff_tool
    agents:
      queue: nano
  - wait
  - label: "annotate with diff"
    command:
      - "buildkite-agent artifact download reports/api_diff.txt ."
      - "if grep -q '✖' reports/api_diff.txt; then export STYLE=warning; else export STYLE=info; fi &&  (echo '```term' && cat reports/api_diff.txt && echo '```') | buildkite-agent annotate --style=$STYLE"
    agents:
      queue: nano

  - label: "{{ matrix }} (library)"
    command: "./builds/run_sbt_tests.sh {{ matrix }}"
    matrix:
      - "display"
      - "search_common"
      - "stacks"

    agents:
      queue: "scala"

  - label: "{{ matrix }} (app)"
    command: |
      ./builds/run_sbt_tests.sh {{ matrix }}
      ./builds/build_sbt_image.sh {{ matrix }} "$BUILDKITE_COMMIT"

      if [[ "$BUILDKITE_BRANCH" == "main" ]]
      then
        ./builds/publish_sbt_image_to_ecr.sh {{ matrix }} "$BUILDKITE_COMMIT"
      fi

    matrix:
      - "search"
      - "items"
      - "snapshot_generator"

    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"

    agents:
      queue: "scala"

  - label: "{{ matrix }} (app)"
    command: |
      ./builds/run_sbt_tests.sh {{ matrix }}
      ./builds/build_sbt_image.sh {{ matrix }} "$BUILDKITE_COMMIT"

      if [[ "$BUILDKITE_BRANCH" == "main" ]]
      then
        ./builds/publish_sbt_image_to_ecr.sh {{ matrix }} "$BUILDKITE_COMMIT"
      fi

    matrix:
      - "requests"

    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::770700576653:role/identity-ci"

    agents:
      queue: "scala"

  - label: "Concepts API (run tests)"
    key: "concepts-test"
    plugins:
      - docker-compose#v3.9.0:
          run: "concepts"
          command: ["yarn", "test"]

  - label: "Concepts API (publish image)"
    depends_on:
      - "concepts-test"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.9.0:
          push:
            - concepts:756629837203.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/concepts:ref.${BUILDKITE_COMMIT}
            - concepts:756629837203.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/concepts:latest

  - command: .buildkite/scripts/test_rank.sh
    label: "rank"
    env:
      QUERY_ENV: "candidate"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"

  - wait

  - label: trigger stage deploy
    branches: "main"
    trigger: "catalogue-api-deploy-stage"
    async: true
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
