steps:
  - label: "Diff tool: Compare stage & prod"
    branches: "main"
    artifact_paths: "reports/*"
    plugins:
      - docker-compose#v3.5.0:
          run: diff_tool
    agents:
      queue: nano

  - wait
  - label: "annotate with diff"
    command: |
      buildkite-agent artifact download reports/api_diff.txt .
      if grep -q '✖' reports/api_diff.txt; then 
        export STYLE=warning; 
      else 
        export STYLE=info; 
      fi
      (echo '```term' && cat reports/api_diff.txt && echo '```') | buildkite-agent annotate --style=$$STYLE
    agents:
      queue: nano

  - block: ":rocket: Deploy to prod?"
    prompt: "Deploying ref.$BUILDKITE_COMMIT: Have you checked staging & diff-tool?"

  - label: "Deploy (catalogue prod)"
    branches: "main"
    concurrency: 1
    concurrency_group: catalogue/deploy-prod
    command: |
      ENV_TAG="env.prod" ./builds/update_ecr_image_tag.sh \
        uk.ac.wellcome/concepts \
        uk.ac.wellcome/items \
        uk.ac.wellcome/search

      CLUSTER="catalogue-api-2021-04-26" ./builds/deploy_ecs_services.sh \
        prod-concepts-api \
        prod-items-api \
        prod-search-api

    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"

    agents:
      queue: nano

  - label: "Deploy (snapshot generator)"
    branches: "main"
    concurrency: 1
    concurrency_group: snapshots/deploy-prod
    command: |
      ENV_TAG="env.prod" ./builds/update_ecr_image_tag.sh \
        uk.ac.wellcome/snapshot_generator

      CLUSTER="data-api" ./builds/deploy_ecs_services.sh \
        snapshot_generator-prod

    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"

    agents:
      queue: nano

  - label: "Deploy (requests prod)"
    branches: "main"
    concurrency: 1
    concurrency_group: requests/deploy-prod
    command: |
      ENV_TAG="env.prod" ./builds/update_ecr_image_tag.sh \
        uk.ac.wellcome/requests
      CLUSTER="identity-prod" ./builds/deploy_ecs_services.sh \
        requests-prod

    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::770700576653:role/identity-ci"

    agents:
      queue: nano

  - wait

  - label: "Smoke Tests: Catalogue API (prod)"
    branches: "main"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::130871440101:role/experience-ci"
      - docker-compose#v3.5.0:
          run: smoke_test_catalogue_api_stage
          command: ["yarn", "run", "smokeTestCatalogueApiProd"]
          env:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
            - AWS_REGION=eu-west-1

  - label: "E2E Tests: PROD Front-end / PROD Catalogue API"
    branches: "main"
    trigger: "experience-e2e"
    soft_fail: true # Added 2023-06-02 due to issues with flaky tests - to be removed as soon as is practical
    build:
      env:
        PLAYWRIGHT_BASE_URL: https://wellcomecollection.org

  - label: "Rank tests: Catalogue API PROD ({{matrix}})"
    matrix:
      - "works"
      - "images"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
      - ecr#v2.7.0:
          login: true
      - docker#v5.8.0:
          image: 756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/rank:latest
          command:
            - "test"
            - "--content-type={{matrix}}"
            - "--cluster=pipeline-prod"
            - "--query=https://api.wellcomecollection.org/catalogue/v2"
          mount-checkout: false
          always-pull: true
          propagate-environment: true
          propagate-aws-auth-tokens: true
          shell: false

  - wait

  - label: "Bump the concepts-pipeline (if necessary)"
    command: |
      pip3 install boto3 httpx
      python3 .buildkite/scripts/open_concepts_pipeline_pr.py
    agents:
      queue: nano
