steps:
  # - label: "Diff tool: Compare stage & prod"
  #   branches: "main"
  #   plugins:
  #     - wellcomecollection/aws-assume-role#v0.2.2:
  #         role: "arn:aws:iam::756629837203:role/platform-ci"
  #     - docker-compose#v3.5.0:
  #         run: diff_tool
  #         env:
  #           - AWS_ACCESS_KEY_ID
  #           - AWS_SECRET_ACCESS_KEY
  #           - AWS_SESSION_TOKEN
  #           - AWS_REGION=eu-west-1
  #   agents:
  #     queue: nano
  #
  # - wait

  - block: ":rocket: Deploy to prod?"
    prompt: "Deploying ref.$BUILDKITE_COMMIT: Have you checked staging & diff-tool?"

  - label: "Deploy (catalogue prod)"
    branches: "main"
    plugins:
      - docker#v3.5.0:
          image: 760097843905.dkr.ecr.eu-west-1.amazonaws.com/wellcome/weco-deploy:5.6
          workdir: /repo
          mount-ssh-agent: true
          command: [
              "--project-id", "catalogue_api",
              "--confirm",
              "release-deploy",
              "--from-label", "ref.$BUILDKITE_COMMIT",
              "--environment-id", "prod",
              "--description", $BUILDKITE_BUILD_URL,
              "--confirmation-wait-for", 3600 ]
    agents:
      queue: nano
  - label: "Deploy (requests prod)"
    branches: "main"
    plugins:
      - docker#v3.5.0:
          image: 760097843905.dkr.ecr.eu-west-1.amazonaws.com/wellcome/weco-deploy:5.6
          workdir: /repo
          mount-ssh-agent: true
          command: [
              "--project-id", "requests_api",
              "--confirm",
              "release-deploy",
              "--from-label", "ref.$BUILDKITE_COMMIT",
              "--environment-id", "prod",
              "--description", $BUILDKITE_BUILD_URL,
              "--confirmation-wait-for", 3600 ]
    agents:
      queue: nano

  - wait

  - label: "Smoke Tests: Catalogue API (prod)"
    branches: "main"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::130871440101:role/experience-ci"
      - docker-compose#v3.5.0:
          run: smoke_test_catalogue_api_stage
          command: [ "yarn", "run", "smokeTestCatalogueApiProd" ]
          env:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
            - AWS_REGION=eu-west-1

  - label: "E2E Tests: PROD Front-end / PROD Catalogue API"
    branches: "main"
    trigger: "experience-e2e"
    build:
      env:
        PLAYWRIGHT_BASE_URL: https://wellcomecollection.org

  - label: "Rank tests: Catalogue API (prod)"
    command: ./.buildkite/scripts/test_rank.sh
    env:
      QUERY_ENV: "production"
