steps:
  - label: "Diff tool: Compare stage & prod"
    branches: "main"
    plugins:
      - docker-compose#v3.5.0:
          run: diff_tool
    agents:
      queue: nano

  - wait

  - block: ":rocket: Deploy to prod?"
    prompt: "Deploying ref.$BUILDKITE_COMMIT: Have you checked staging & diff-tool?"

  - label: "Deploy (catalogue prod)"
    branches: "main"
    command: |
      ENV_TAG="env.prod" ./builds/update_ecr_image_tag.sh \
        uk.ac.wellcome/concepts \
        uk.ac.wellcome/items \
        uk.ac.wellcome/search

      CLUSTER="catalogue-api-2021-04-26" ./builds/deploy_ecs_services.sh \
        prod-concepts-api \
        prod-items-api \
        prod-search-api

    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"

    agents:
      queue: nano

  - label: "Deploy (requests prod)"
    branches: "main"
    command: |
      ENV_TAG="env.prod" ./builds/update_ecr_image_tag.sh \
        uk.ac.wellcome/requests
      CLUSTER="identity-prod" ./builds/redeploy_ecs_services.sh \
        requests-prod

    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::770700576653:role/identity-ci"

    agents:
      queue: nano

  - wait

  - label: "Smoke Tests: Catalogue API (prod)"
    branches: "main"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::130871440101:role/experience-ci"
      - docker-compose#v3.5.0:
          run: smoke_test_catalogue_api_stage
          command: ["yarn", "run", "smokeTestCatalogueApiProd"]
          env:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
            - AWS_REGION=eu-west-1

  - label: "E2E Tests: PROD Front-end / PROD Catalogue API"
    branches: "main"
    trigger: "experience-e2e"
    build:
      env:
        PLAYWRIGHT_BASE_URL: https://wellcomecollection.org

  - label: "Rank tests: Catalogue API (prod)"
    command: ./.buildkite/scripts/test_rank.sh
    env:
      QUERY_ENV: "production"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
