steps:
  - command: .buildkite/scripts/run_autoformat.py
    label: "autoformat"
  - wait
  - command: .buildkite/scripts/run_job.py display
    label: "display"
  - command: .buildkite/scripts/run_job.py stacks
    label: "stacks_common"
  - wait
  - command: .buildkite/scripts/run_job.py search
    label: "Search API (Works & Images)"
  - command: .buildkite/scripts/run_job.py items
    label: "Stacks: Items API"
  - command: .buildkite/scripts/run_job.py requests
    label: "Stacks: Requests API"
  - command: .buildkite/scripts/run_job.py snapshot_generator
    label: "snapshot generator"
  - wait
  - command: .buildkite/scripts/tag_commit_as_latest.py
    label: "tag commit as latest"
  - wait
  - label: release to stage
    if: build.branch == "main"
    plugins:
      - docker#v3.5.0:
          image: 760097843905.dkr.ecr.eu-west-1.amazonaws.com/wellcome/weco-deploy:5.6.16
          workdir: /repo
          mount-ssh-agent: true
          command: [
              "--project-id", "catalogue_api",
              "--confirm",
              "release-deploy",
              "--from-label", "latest",
              "--environment-id", "stage",
              "--description", $BUILDKITE_BUILD_URL,
              "--confirmation-wait-for", 3600]
  - wait
  - label: "Integration pipeline"
    trigger: "integration"
    async: true

