steps:
  - command: ./.buildkite/scripts/test_rank.sh
    env:
      QUERY_ENV: "production"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
