steps:
  - command: |
      ./builds/run_formatting.sh
      .buildkite/scripts/push_autoformatting_changes.sh
      ./builds/run_linting.sh
    label: "autoformat"
    agents:
      queue: "scala"

    # We increase the priority of this task because it may push a commit
    # and trigger a new build; if so, we want that to happen ASAP.
    priority: 1

  - label: "{{ matrix }} (library)"
    command: "./builds/run_sbt_tests.sh {{ matrix }}"
    matrix:
      - "display"
      - "search_common"
      - "stacks"

    agents:
      queue: "scala"

  - label: "{{ matrix }} (app)"
    command: |
      ./builds/run_sbt_tests.sh {{ matrix }}
      ./builds/build_sbt_image.sh {{ matrix }} "$BUILDKITE_COMMIT"

      if [[ "$BUILDKITE_BRANCH" == "main" ]]
      then
        ./builds/publish_sbt_image_to_ecr.sh {{ matrix }} "$BUILDKITE_COMMIT"
      fi

    matrix:
      - "search"
      - "items"
      - "snapshot_generator"

    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"

    agents:
      queue: "scala"

  - label: "{{ matrix }} (app)"
    command: |
      ./builds/run_sbt_tests.sh {{ matrix }}
      ./builds/build_sbt_image.sh {{ matrix }} "$BUILDKITE_COMMIT"

      if [[ "$BUILDKITE_BRANCH" == "main" ]]
      then
        ./builds/publish_sbt_image_to_ecr.sh {{ matrix }} "$BUILDKITE_COMMIT"
      fi

    matrix:
      - "requests"

    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::770700576653:role/identity-ci"

    agents:
      queue: "scala"

  - label: "Concepts API (run tests)"
    key: "concepts-test"
    plugins:
      - docker-compose#v3.9.0:
          run: "concepts"
          command: ["yarn", "test"]

  - label: "Concepts API (publish image)"
    depends_on:
      - "concepts-test"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::756629837203:role/catalogue-ci"
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.9.0:
          push:
            - concepts:756629837203.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/concepts:ref.${BUILDKITE_COMMIT}
            - concepts:756629837203.dkr.ecr.eu-west-1.amazonaws.com/uk.ac.wellcome/concepts:latest

  - label: "Rank: test in-branch query against staging cluster"
    command: "test --content-type=works --cluster=pipeline-stage --query=/resources/WorksMultiMatcherQueryTemplate.json"
    plugins:
      - ecr#v2.7.0:
          login: true
          assume_role:
            role_arn: "arn:aws:iam::756629837203:role/catalogue-ci"
      - docker#v5.8.0:
          image: 756629837203.dkr.ecr.eu-west-1.amazonaws.com/weco/rank:latest
          volumes:
            - "./search/src/main/resources:/resources"
          always-pull: true
          propagate-aws-auth-tokens: true

  - wait

  - label: trigger stage deploy
    branches: "main"
    trigger: "catalogue-api-deploy-stage"
    async: true
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        BUILDKITE_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
