// This code is copied from the catalogue-pipeline repo.
//
// Do not edit this file -- edit the copy in the pipeline repo, commit
// those changes to main and then copy them into this repo.
//
// https://raw.githubusercontent.com/wellcomecollection/catalogue-pipeline/main/common/source_model/src/main/scala/weco/catalogue/source_model/sierra/source/Status.scala

package weco.catalogue.source_model.sierra.source

object Status {
  val Available = "-"
  val PermissionRequired = "y"
  val Missing = "m"
  val Unavailable = "r"
  val Closed = "h"
  val OnHoldshelf = "!"
  val Withdrawn = "x"
}
