# Runs auto-formatting script on push to any branch
name: "Scala auto-formatting"

on: push

permissions:
  id-token: write
  contents: write

jobs:
  autoformat:
    uses: wellcomecollection/.github/.github/workflows/autoformat.yml@make-reformatting-workflow-reusable
