# Runs auto-formatting script on push to any branch
name: "Run auto formatting"

permissions:
  id-token: write
  contents: read

on: push

jobs:
  autoformat:
    name: autoformat
    runs-on: ubuntu-latest
    steps:
      - name: Check out project
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        id: aws_credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GHA_SCALA_FORMATTING_ROLE_ARN }}
          output-credentials: true

      - name: Log in to private ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Run formatting
        run: bash ./builds/run_formatting.sh
        env:
          aws-region: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ steps.aws_credentials.outputs.aws-access-key-id }}
          AWS_SECRET_KEY: ${{ steps.aws_credentials.outputs.aws-secret-access-key }}


