# Runs auto-formatting script on push to any branch
name: "Run auto formatting"

permissions:
  id-token: write
  contents: read

on: push

jobs:
  autoformat:
    name: autoformat
    runs-on: ubuntu-latest
    steps:
      - name: Check out project
        uses: actions/checkout@v4

      - name: Configure AWS credentials for ECR
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GHA_PLATFORM_ECR_READ_ROLE_ARN }}

      - name: Log in to private ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Configure AWS credentials for S3
        id: s3_credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.S3_SCALA_RELEASES_READ_ROLE_ARN }}

      - name: Run formatting
        run: |
          aws configure set role_arn "${{ secrets.S3_SCALA_RELEASES_READ_ROLE_ARN }}"
          bash ./builds/run_formatting.sh
