# Runs auto-formatting script on push to any branch
name: "Run auto formatting"

permissions:
  id-token: write
  contents: read

on: push

jobs:
  autoformat:
    name: autoformat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GHA_PLATFORM_ECR_READ_ROLE_ARN }}
      - uses: aws-actions/amazon-ecr-login@v2
      - run: bash ./builds/run_formatting.sh
