# .github/workflows/dependency-graph.yml
name: Update Dependency Graph
on:
  push:
    branches:
      - main
      - rk/test-dep-updates

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - name: Setup sbt
        uses: sbt/setup-sbt@v1.1.0
      - uses: scalacenter/sbt-dependency-submission@v2
